"""empty message

Revision ID: 5099cf43e482
Revises: ab48517559dc
Create Date: 2019-11-21 11:35:02.456190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5099cf43e482'
down_revision = 'ab48517559dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_reclamacao',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('reclamacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reclamacao_id'], ['reclamacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_reclamacao')
    # ### end Alembic commands ###
