"""empty message

Revision ID: 931b2a0fabc8
Revises: de7aa586a4c5
Create Date: 2019-11-21 20:48:21.064970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931b2a0fabc8'
down_revision = 'de7aa586a4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclamacao', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reclamacao', 'created_at')
    # ### end Alembic commands ###
