"""empty message

Revision ID: 988955190655
Revises: cb766d43e410
Create Date: 2019-11-21 09:30:36.467428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988955190655'
down_revision = 'cb766d43e410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclamacao', sa.Column('fechado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reclamacao', 'fechado')
    # ### end Alembic commands ###
