"""empty message

Revision ID: cb766d43e410
Revises: de791f1bdf66
Create Date: 2019-11-21 09:18:19.519736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb766d43e410'
down_revision = 'de791f1bdf66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclamacao', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reclamacao', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reclamacao', type_='foreignkey')
    op.drop_column('reclamacao', 'usuario_id')
    # ### end Alembic commands ###
