"""empty message

Revision ID: de791f1bdf66
Revises: 256f8a462155
Create Date: 2019-11-21 09:07:37.325591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de791f1bdf66'
down_revision = '256f8a462155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclamacao', sa.Column('descricao', sa.String(length=500), nullable=True))
    op.drop_column('reclamacao', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclamacao', sa.Column('desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('reclamacao', 'descricao')
    # ### end Alembic commands ###
