"""empty message

Revision ID: de7aa586a4c5
Revises: 5099cf43e482
Create Date: 2019-11-21 20:37:56.188149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7aa586a4c5'
down_revision = '5099cf43e482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reclamacao', 'tempo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclamacao', sa.Column('tempo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
